name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Compilation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make KR Server
      run: cd server && make
    - name: Make KR Server Portable (Statically Linked)
      run: cd server && make portable
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
